# Generated by Django 3.2.13 on 2023-11-28 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20231128_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('card_number', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='卡号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('department', models.CharField(max_length=100, verbose_name='单位')),
                ('reader_type', models.CharField(max_length=50, verbose_name='类型')),
                ('level', models.CharField(max_length=50, verbose_name='级别')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(verbose_name='借书时间')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='还书时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.reader')),
            ],
        ),
    ]
