# Generated by Django 3.2.13 on 2023-12-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20231212_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
    ]
