# Generated by Django 3.2.13 on 2024-01-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_remove_borrow_fine_processed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrow',
            unique_together={('book', 'reader')},
        ),
    ]
