# Generated by Django 3.2.13 on 2023-12-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20231128_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='应还书日期'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='总罚款金额'),
        ),
        migrations.AddField(
            model_name='borrow',
            name='fine_per_day',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='每天罚款金额'),
        ),
    ]
