# Generated by Django 3.2.13 on 2023-12-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20231209_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='fine_amount',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='fine_per_day',
        ),
    ]
